apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::375963731961:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::375963731961:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K2ECBEVLIMQW
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-21T19:18:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5224"
  uid: 16bd679b-0e5a-428e-b2fc-316afcbbe788
